package com.hhit.entity;

import java.util.Set;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Chapter.java
//  @ Date : 2016/5/6
//  @ Author : 
//
//
public class Chapter {
	private Integer id;
	private String chapterNum;
	private String chapterName;
	
	private String courseName;
	//new add
	private String url;
	
	private Course course;
	private Chapter parent;
	private Set<Chapter> children;

	/**
	 * 默认构造函数
	 */
	public Chapter() {
	}
	/**
	 * 构造函数
	 */
	public Chapter(String chapterNum, String chapterName,String url, String courseName,
			Course course, Chapter parent) {
		super();
		this.chapterNum = chapterNum;
		this.chapterName = chapterName;
		this.url=url;
		this.courseName = courseName;
		this.course = course;
		this.parent = parent;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getChapterNum() {
		return chapterNum;
	}

	public void setChapterNum(String chapterNum) {
		this.chapterNum = chapterNum;
	}

	public String getChapterName() {
		return chapterName;
	}

	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Chapter getParent() {
		return parent;
	}

	public void setParent(Chapter parent) {
		this.parent = parent;
	}

	public Set<Chapter> getChildren() {
		return children;
	}

	public void setChildren(Set<Chapter> children) {
		this.children = children;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	
}
