package com.hhit.entity;

import java.util.Set;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DataType.java
//  @ Date : 2016/4/9
//  @ Author : 
//
//




public class DataType implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String dataTypeNum;
	private String dataTypeName;
	private Set<DataDict> dataDicts;
	
	/**
	 * 默认构造函数
	 */
	public DataType(){
		
	}
	
	/**
	 * 构造函数
	 */
	public DataType(String num,String name){
		dataTypeNum=num;
		dataTypeName=name;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDataTypeNum() {
		return dataTypeNum;
	}
	public void setDataTypeNum(String dataTypeNum) {
		this.dataTypeNum = dataTypeNum;
	}
	public String getDataTypeName() {
		return dataTypeName;
	}
	public void setDataTypeName(String dataTypeName) {
		this.dataTypeName = dataTypeName;
	}
	public Set<DataDict> getDataDicts() {
		return dataDicts;
	}
	public void setDataDicts(Set<DataDict> dataDicts) {
		this.dataDicts = dataDicts;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
