package com.hhit.entity;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DataDict.java
//  @ Date : 2016/4/9
//  @ Author : 
//
//




public class DataDict implements java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String dictNum;
	private String dictName;
	private String description;
	private DataType dataType;
	
	/**
	 * 默认构造函数
	 */
	public DataDict(){
		
	}
	/**
	 * 构造函数
	 */
	public DataDict(String num,String name,DataType d){
		dictNum=num;
		dictName=name;
		dataType=d;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getDictNum() {
		return dictNum;
	}
	public void setDictNum(String dictNum) {
		this.dictNum = dictNum;
	}
	public String getDictName() {
		return dictName;
	}
	public void setDictName(String dictName) {
		this.dictName = dictName;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public DataType getDataType() {
		return dataType;
	}
	public void setDataType(DataType dataType) {
		this.dataType = dataType;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
}
