package com.hhit.entity;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Favorite.java
//  @ Date : 2016/5/3
//  @ Author : 
//
//

public class Favorite {
	private Integer id;
	private String professionType;
	private String name;
	private String info;
	private String url;
	private String imgurl;

	private SpiderCourse spiderCourse;
	private Student student;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProfessionType() {
		return professionType;
	}

	public void setProfessionType(String professionType) {
		this.professionType = professionType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	public SpiderCourse getSpiderCourse() {
		return spiderCourse;
	}

	public void setSpiderCourse(SpiderCourse spiderCourse) {
		this.spiderCourse = spiderCourse;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
