package com.hhit.entity;

import java.sql.Timestamp;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : QuestionErrorRecord.java
//  @ Date : 2016/5/15
//  @ Author : 
//
//




public class QuestionErrorRecord {
	private Integer id;
	private String stuNum;
	private Timestamp addTime;
	
	private TestQuestion testQuestion;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getStuNum() {
		return stuNum;
	}
	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}
	public TestQuestion getTestQuestion() {
		return testQuestion;
	}
	public void setTestQuestion(TestQuestion testQuestion) {
		this.testQuestion = testQuestion;
	}
	public Timestamp getAddTime() {
		return addTime;
	}
	public void setAddTime(Timestamp addTime) {
		this.addTime = addTime;
	}
	
}
