package com.hhit.entity;

import java.sql.Timestamp;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SingleChoice.java
//  @ Date : 2016/5/6
//  @ Author : 
//
//

public class SingleChoice {
	private Integer id;
	private Integer questionCode;
	private String knowledgeName;
	private Timestamp modifyTime;
	private Timestamp addTime;
	private String answer;
	private String question;
	private String answerA;
	private String answerB;
	private String answerC;
	private String answerD;
	private Integer difExponent;
	private Integer usedCount;
	private String questionType;
	
	private String teacherNum;
	
	private Course course;
	private Chapter chapter;
	
	
	/**
	 * 默认构造函数
	 */
	public SingleChoice() {
		
	}
	/**
	 * 构造函数
	 */
	public SingleChoice(String teacherNum, Course course, String knowledgeName,
			String question, String answer, String answerA, String answerB,
			String answerC, String answerD, Integer difExponent) {
		super();
		this.teacherNum = teacherNum;
		this.course = course;
		this.knowledgeName = knowledgeName;
		this.question = question;
		this.answer = answer;
		this.answerA = answerA;
		this.answerB = answerB;
		this.answerC = answerC;
		this.answerD = answerD;
		this.difExponent = difExponent;
	}

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getQuestionCode() {
		return questionCode;
	}
	public void setQuestionCode(Integer questionCode) {
		this.questionCode = questionCode;
	}

	public String getKnowledgeName() {
		return knowledgeName;
	}
	public void setKnowledgeName(String knowledgeName) {
		this.knowledgeName = knowledgeName;
	}
	public Timestamp getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(Timestamp modifyTime) {
		this.modifyTime = modifyTime;
	}
	public Timestamp getAddTime() {
		return addTime;
	}
	public void setAddTime(Timestamp addTime) {
		this.addTime = addTime;
	}
	public String getAnswer() {
		return answer;
	}
	public void setAnswer(String answer) {
		this.answer = answer;
	}
	public String getQuestion() {
		return question;
	}
	public void setQuestion(String question) {
		this.question = question;
	}
	public String getAnswerA() {
		return answerA;
	}
	public void setAnswerA(String answerA) {
		this.answerA = answerA;
	}
	public String getAnswerB() {
		return answerB;
	}
	public void setAnswerB(String answerB) {
		this.answerB = answerB;
	}
	public String getAnswerC() {
		return answerC;
	}
	public void setAnswerC(String answerC) {
		this.answerC = answerC;
	}
	public String getAnswerD() {
		return answerD;
	}
	public void setAnswerD(String answerD) {
		this.answerD = answerD;
	}
	public Integer getUsedCount() {
		return usedCount;
	}
	public void setUsedCount(Integer usedCount) {
		this.usedCount = usedCount;
	}
	public String getQuestionType() {
		return questionType;
	}
	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}
	public Course getCourse() {
		return course;
	}
	public void setCourse(Course course) {
		this.course = course;
	}
	public Chapter getChapter() {
		return chapter;
	}
	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}
	public Integer getDifExponent() {
		return difExponent;
	}
	public void setDifExponent(Integer difExponent) {
		this.difExponent = difExponent;
	}
	public String getTeacherNum() {
		return teacherNum;
	}
	public void setTeacherNum(String teacherNum) {
		this.teacherNum = teacherNum;
	}
	
	
}
