package com.hhit.entity;

import java.util.Set;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpiderCourse.java
//  @ Date : 2016/4/18
//  @ Author : 
//
//




public class SpiderCourse {
	private Integer id;
	private String professionType;
	private String name;
	private String url;
	private String info;
	private String imgUrl;
	
	private Set<SpiderChapter> spiderChapters;
	private Set<SpiderDocument> spiderDocuemnts;
	/** 默认构造函数 */
	public SpiderCourse(){
		
	}
	/** 构造函数 */
	public SpiderCourse(String na,String ur,String in,String pr){
		name=na;
		url=ur;
		info=in;
		professionType=pr;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getProfessionType() {
		return professionType;
	}
	public void setProfessionType(String professionType) {
		this.professionType = professionType;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public Set<SpiderChapter> getSpiderChapters() {
		return spiderChapters;
	}
	public void setSpiderChapters(Set<SpiderChapter> spiderChapters) {
		this.spiderChapters = spiderChapters;
	}
	public Set<SpiderDocument> getSpiderDocuemnts() {
		return spiderDocuemnts;
	}
	public void setSpiderDocuemnts(Set<SpiderDocument> spiderDocuemnts) {
		this.spiderDocuemnts = spiderDocuemnts;
	}
	public String getImgUrl() {
		return imgUrl;
	}
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
	
	
	
}
