package com.hhit.entity;


//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpiderProfession.java
//  @ Date : 2016/4/15
//  @ Author : 
//
//

public class SpiderProfession{

	private Integer id;

	private String professionName;
	private Integer courseCount;
	private String url;
	private String professionType;
	
	/** 默认构造函数 */
	public SpiderProfession(){
		
	}
	/** 构造函数 */
	public SpiderProfession(String p,Integer c,String u,String pt){
		professionName=p;
		courseCount=c;
		url=u;
		professionType=pt;
	}
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getProfessionName() {
		return professionName;
	}
	public void setProfessionName(String professionName) {
		this.professionName = professionName;
	}
	public Integer getCourseCount() {
		return courseCount;
	}
	public void setCourseCount(Integer courseCount) {
		this.courseCount = courseCount;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getProfessionType() {
		return professionType;
	}
	public void setProfessionType(String professionType) {
		this.professionType = professionType;
	}
	
	
}
