package com.hhit.entity;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpiderDocument.java
//  @ Date : 2016/4/18
//  @ Author : 
//
//




public class SpiderDocument {
	private Integer id;
	private String name;
	private String url;
	private String author;
	private String publish;
	private String imgUrl;
	private SpiderCourse spiderCourse;
	/** 默认构造函数 */
	public SpiderDocument(){
		
	}
	/** 构造函数 */
	public SpiderDocument(String na,String ur,String au,String pu,String im,SpiderCourse sp){
		name=na; 
		url=ur;    
		author=au; 
		publish=pu;
		imgUrl=im; 
		spiderCourse=sp;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getAuthor() {
		return author;
	}
	public void setAuthor(String author) {
		this.author = author;
	}
	public String getPublish() {
		return publish;
	}
	public void setPublish(String publish) {
		this.publish = publish;
	}
	public String getImgUrl() {
		return imgUrl;
	}
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
	public SpiderCourse getSpiderCourse() {
		return spiderCourse;
	}
	public void setSpiderCourse(SpiderCourse spiderCourse) {
		this.spiderCourse = spiderCourse;
	}
	
}
