package com.hhit.entity;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpiderCourse.java
//  @ Date : 2016/4/18
//  @ Author : 
//
//




public class SpiderCourse {
	private Integer id;
	private String professionType;
	private String name;
	private String info;
	/** 默认构造函数 */
	public SpiderCourse(){
		
	}
	/** 构造函数 */
	public SpiderCourse(String na,String in,String pr){
		name=na;
		info=in;
		professionType=pr;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getProfessionType() {
		return professionType;
	}
	public void setProfessionType(String professionType) {
		this.professionType = professionType;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	
	
}
