package com.hhit.entity;

import java.sql.Timestamp;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StuFlowerInfo.java
//  @ Date : 2016/5/27
//  @ Author : 
//
//

public class StuFlowerInfo {
	private Integer id;
	private String stuNum;
	private Timestamp addTime;
	private String courseName;
	
	private String teaNum;
	
	private StuScoreRecord stuScoreRecord;
	
	/**
	 * 默认构造函数
	 */
	public StuFlowerInfo() {
		super();
	}
	/**
	 * 构造函数
	 */
	public StuFlowerInfo(String stuNum, Timestamp addTime, String courseName,
			String teaNum,StuScoreRecord stuScoreRecord) {
		super();
		this.stuNum = stuNum;
		this.addTime = addTime;
		this.courseName = courseName;
		this.teaNum = teaNum;
		this.stuScoreRecord=stuScoreRecord;
	}

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getStuNum() {
		return stuNum;
	}
	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}
	public Timestamp getAddTime() {
		return addTime;
	}
	public void setAddTime(Timestamp addTime) {
		this.addTime = addTime;
	}
	public String getCourseName() {
		return courseName;
	}
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}
	public String getTeaNum() {
		return teaNum;
	}
	public void setTeaNum(String teaNum) {
		this.teaNum = teaNum;
	}
	public StuScoreRecord getStuScoreRecord() {
		return stuScoreRecord;
	}
	public void setStuScoreRecord(StuScoreRecord stuScoreRecord) {
		this.stuScoreRecord = stuScoreRecord;
	}
}
