package com.hhit.entity;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StuPaperAccount.java
//  @ Date : 2016/5/19
//  @ Author : 
//
//




public class StuPaperAccount {
	private Integer id;
	private String stuName;
	private String stuNum;
	private Integer submitCount;
	private Float averageScore;
	
	private Class_ class_;
	private Course course;
	/**
	 * 默认构造函数
	 */
	public StuPaperAccount() {
		super();
		// TODO Auto-generated constructor stub
	}
	/**
	 * 构造函数
	 */
	
	public StuPaperAccount(String stuName, String stuNum, Integer submitCount,
			Float averageScore, Class_ class_,Course course) {
		super();
		this.stuName = stuName;
		this.stuNum = stuNum;
		this.submitCount = submitCount;
		this.averageScore = averageScore;
		this.class_ = class_;
		this.course=course;
	}


	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getStuName() {
		return stuName;
	}
	public void setStuName(String stuName) {
		this.stuName = stuName;
	}
	public String getStuNum() {
		return stuNum;
	}
	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}
	public Integer getSubmitCount() {
		return submitCount;
	}
	public void setSubmitCount(Integer submitCount) {
		this.submitCount = submitCount;
	}
	public Float getAverageScore() {
		return averageScore;
	}
	public void setAverageScore(Float averageScore) {
		this.averageScore = averageScore;
	}
	public Class_ getClass_() {
		return class_;
	}
	public void setClass_(Class_ class_) {
		this.class_ = class_;
	}
	public Course getCourse() {
		return course;
	}
	public void setCourse(Course course) {
		this.course = course;
	}
	
	
}
