package com.hhit.entity;

import java.sql.Timestamp;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Task.java
//  @ Date : 2016/4/7
//  @ Author : 
//
//
import java.util.Set;




public class Task implements java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String taskName;
	private Timestamp releaseTime;
	private Timestamp endDate;
	private String description;
	private Course course;
	private Set<SubmitTask> submitTasks;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getTaskName() {
		return taskName;
	}
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}
	public Timestamp getReleaseTime() {
		return releaseTime;
	}
	public void setReleaseTime(Timestamp releaseTime) {
		this.releaseTime = releaseTime;
	}
	public Timestamp getEndDate() {
		return endDate;
	}
	public void setEndDate(Timestamp endDate) {
		this.endDate = endDate;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Course getCourse() {
		return course;
	}
	public void setCourse(Course course) {
		this.course = course;
	}
	public Set<SubmitTask> getSubmitTasks() {
		return submitTasks;
	}
	public void setSubmitTasks(Set<SubmitTask> submitTasks) {
		this.submitTasks = submitTasks;
	}
	
	
}
