package com.hhit.entity;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TestQuestion.java
//  @ Date : 2016/5/12
//  @ Author : 
//
//

public class TestQuestion {
	private Integer id;

	private Judgement judgement;
	private SingleChoice singleChoice;
	private TestPaper testPaper;

	/**
	 * 默认构造函数
	 */
	public TestQuestion() {

	}

	/**
	 * 构造函数
	 */
	public TestQuestion(Judgement judgement, SingleChoice singleChoice,
			TestPaper testPaper) {
		this.judgement = judgement;
		this.singleChoice = singleChoice;
		this.testPaper = testPaper;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Judgement getJudgement() {
		return judgement;
	}

	public void setJudgement(Judgement judgement) {
		this.judgement = judgement;
	}

	public SingleChoice getSingleChoice() {
		return singleChoice;
	}

	public void setSingleChoice(SingleChoice singleChoice) {
		this.singleChoice = singleChoice;
	}

	public TestPaper getTestPaper() {
		return testPaper;
	}

	public void setTestPaper(TestPaper testPaper) {
		this.testPaper = testPaper;
	}

}
