package com.hhit.entity;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TestQuestion.java
//  @ Date : 2016/5/12
//  @ Author : 
//
//




public class TestQuestion {
	private Integer id;
	
	
	private Judgement judgement;
	private SingleChoice singleChoice;
	private TestPaper testPaper;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Judgement getJudgement() {
		return judgement;
	}
	public void setJudgement(Judgement judgement) {
		this.judgement = judgement;
	}
	public SingleChoice getSingleChoice() {
		return singleChoice;
	}
	public void setSingleChoice(SingleChoice singleChoice) {
		this.singleChoice = singleChoice;
	}
	public TestPaper getTestPaper() {
		return testPaper;
	}
	public void setTestPaper(TestPaper testPaper) {
		this.testPaper = testPaper;
	}
	
}
