package com.hhit.entity;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VisitCourseRecord.java
//  @ Date : 2016/5/3
//  @ Author : 
//
//




public class VisitCourseRecord {
	private Integer id;
	private Integer count;
	
	
	private Student student;
	private SpiderCourse spiderCourse;
	
	/**
	 * 默认构造函数 
	 */
	public VisitCourseRecord(){
		
	}
	/**
	 * 构造函数 
	 */
	public VisitCourseRecord(Student stu,SpiderCourse sc,Integer cou){
		student=stu;
		spiderCourse=sc;
		count=cou;
	}
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getCount() {
		return count;
	}
	public void setCount(Integer count) {
		this.count = count;
	}
	public Student getStudent() {
		return student;
	}
	public void setStudent(Student student) {
		this.student = student;
	}
	public SpiderCourse getSpiderCourse() {
		return spiderCourse;
	}
	public void setSpiderCourse(SpiderCourse spiderCourse) {
		this.spiderCourse = spiderCourse;
	}
	
}
