/*
*######################################
* eWebEditor V9.0 - Advanced online web based WYSIWYG HTML editor.
* Copyright (c) 2003-2013 eWebSoft.com
*
* For further information go to http://www.ewebeditor.net/
* This copyright notice MUST stay intact for use.
*######################################
*/



//#####################################
// Toolbar Items
//#####################################

//Edit
lang["EditMenu"]				= "编辑菜单"
lang["UnDo"]					= "撤消"
lang["ReDo"]					= "恢复"
lang["Cut"]						= "剪切"
lang["Copy"]					= "复制"
lang["Paste"]					= "常规粘贴"
lang["PasteText"]				= "纯文本粘贴"
lang["PasteWord"]				= "从Word粘贴"
lang["Delete"]					= "删除"
lang["RemoveFormat"]			= "删除文字格式"
lang["SelectAll"]				= "全部选中"
lang["UnSelect"]				= "取消选择"
lang["FindReplace"]				= "查找替换..."
lang["SpellCheck"]				= "拼写检查..."
lang["QuickFormat"]				= "一键排版..."
lang["FormatBrush"]				= "格式刷"

// Font
lang["FontMenu"]				= "字体菜单"
lang["Bold"]					= "粗体"
lang["Italic"]					= "斜体"
lang["UnderLine"]				= "下划线"
lang["StrikeThrough"]			= "中划线"
lang["SuperScript"]				= "上标"
lang["SubScript"]				= "下标"
lang["UpperCase"]				= "转大写字母"
lang["LowerCase"]				= "转小写字母"
lang["ForeColor"]				= "字体颜色"
lang["BackColor"]				= "字体背景色"
lang["Big"]						= "字体增大"
lang["Small"]					= "字体减小"

// Paragraph
lang["ParagraphMenu"]			= "段落菜单"
lang["JustifyLeft"]				= "左对齐"
lang["JustifyCenter"]			= "居中对齐"
lang["JustifyRight"]			= "右对齐"
lang["JustifyFull"]				= "两端对齐"
lang["OrderedList"]				= "编号"
lang["UnOrderedList"]			= "项目符号"
lang["Indent"]					= "增加缩进量"
lang["Outdent"]					= "减少缩进量"
lang["Paragraph"]				= "插入段落"
lang["BR"]						= "插入换行符"
lang["ParagraphAttr"]			= "段落属性"

// Component
lang["ComponentMenu"]			= "组件菜单"
lang["Image"]					= "插入或修改图片"
lang["Flash"]					= "插入或修改FLASH动画"
lang["Media"]					= "插入自动播放媒体"
lang["File"]					= "插入附件"
lang["RemoteUpload"]			= "远程文件自动上传"
lang["LocalUpload"]				= "本地文件自动上传"
lang["Fieldset"]				= "插入或修改栏目框"
lang["Iframe"]					= "插入或修改网页帧"
lang["HorizontalRule"]			= "插入或修改水平尺"
lang["Marquee"]					= "插入或修改字幕"
lang["CreateLink"]				= "插入或修改超链接"
lang["Unlink"]					= "取消超链接或标签"
lang["Map"]						= "图形热点链接"
lang["Anchor"]					= "标签管理"

// Object
lang["ObjectMenu"]				= "对象效果菜单"
lang["BgColor"]					= "对象背景颜色"
lang["BackImage"]				= "背景图片"
lang["absolutePosition"]		= "绝对或相对位置"
lang["zIndexBackward"]			= "下移一层"
lang["zIndexForward"]			= "上移一层"
lang["ShowBorders"]				= "显示/隐藏虚框"
lang["ShowBlocks"]				= "显示区块"
lang["Quote"]					= "引用样式"
lang["Code"]					= "代码样式"

// Tool
lang["ToolMenu"]				= "工具菜单"
lang["CSS"]						= "样式"
lang["Symbol"]					= "插入特殊字符"
lang["PrintBreak"]				= "插入打印分页符"
lang["Excel"]					= "插入EXCEL表格"
lang["Emot"]					= "插入表情图标"
lang["EQ"]						= "插入或修改公式"
lang["Art"]						= "插入或修改艺术字"
lang["NowDate"]					= "插入当前日期"
lang["NowTime"]					= "插入当前时间"
lang["ImportWord"]				= "导入Word文档"
lang["ImportExcel"]				= "导入Excel表格"
lang["Template"]				= "插入模板"
lang["Capture"]					= "截屏"
lang["Pagination"]				= "分页管理"
lang["PaginationInsert"]		= "插入分页符"
lang["TitleImage"]				= "设为标题图片"
lang["ImageDoc"]				= "制作图片文库"
lang["ImportPPT"]				= "导入PPT"

// Form
lang["FormMenu"]				= "表单菜单"
lang["FormText"]				= "插入输入框"
lang["FormTextArea"]			= "插入输入区"
lang["FormRadio"]				= "插入单选钮"
lang["FormCheckbox"]			= "插入复选钮"
lang["FormDropdown"]			= "插入下拉框"
lang["FormButton"]				= "插入按钮"

// Table
lang["TableMenu"]				= "表格菜单"
lang["TableInsert"]				= "插入表格..."
lang["TableProp"]				= "表格属性..."
lang["TableCellProp"]			= "单元格属性..."
lang["TableCellSplit"]			= "拆分单元格..."
lang["TableRowProp"]			= "表格行属性..."
lang["TableRowInsertAbove"]		= "插入行（在上方）"
lang["TableRowInsertBelow"]		= "插入行（在下方）"
lang["TableRowMerge"]			= "合并行（向下方）"
lang["TableRowSplit"]			= "拆分行"
lang["TableRowDelete"]			= "删除行"
lang["TableColInsertLeft"]		= "插入列（在左侧）"
lang["TableColInsertRight"]		= "插入列（在右侧）"
lang["TableColMerge"]			= "合并列（向右侧）"
lang["TableColSplit"]			= "拆分列"
lang["TableColDelete"]			= "删除列"

// File&View
lang["FileMenu"]				= "文件视图菜单"
lang["Refresh"]					= "新建"
lang["ModeCode"]				= "代码状态"
lang["ModeEdit"]				= "编辑状态"
lang["ModeText"]				= "文本状态"
lang["ModeView"]				= "预览状态"
lang["SizePlus"]				= "增高编辑区"
lang["SizeMinus"]				= "减小编辑区"
lang["Print"]					= "打印"
lang["ZoomMenu"]				= "缩放菜单"
lang["Maximize"]				= "全屏编辑"
lang["Minimize"]				= "全屏返回"
lang["Save"]					= "保存并返回"
lang["ExpandToolbar"]			= "切换到所有功能"

// Gallery
lang["GalleryMenu"]				= "文件库菜单"
lang["GalleryImage"]			= "浏览图片库"
lang["GalleryFlash"]			= "浏览Flash库"
lang["GalleryMedia"]			= "浏览媒体库"
lang["GalleryFile"]				= "浏览文件库"

// Help
lang["Help"]					= "查看使用帮助"
lang["About"]					= "关于eWebEditor"
lang["Site"]					= "eWebEditor站点"

// Combo
lang["FontName"]				= "字体"
lang["FontNameItem"]			= ["宋体", "黑体", "楷体_GB2312", "仿宋_GB2312", "隶书", "幼圆", "Arial", "Arial Black", "Arial Narrow", "Brush Script MT", "Century Gothic", "Comic Sans MS", "Courier", "Courier New", "MS Sans Serif", "Script", "System", "Times New Roman", "Verdana", "Wide Latin", "Wingdings"]
lang["FontSize"]				= "字号"
lang["FontSizeItem"]			= [ ["42pt","初号"], ["36pt","小初"], ["26pt","一号"], ["24pt","小一"], ["22pt","二号"], ["18pt","小二"], ["16pt","三号"], ["15pt","小三"], ["14pt","四号"], ["12pt","小四"], ["10.5pt","五号"], ["9pt","小五"], ["7.5pt","六号"], ["6.5pt","小六"], ["5.5pt","七号"], ["5pt","八号"], ["5pt","5"], ["5.5pt","5.5"], ["6.5pt","6.5"], ["7.5pt","7.5"], ["8pt","8"], ["9pt","9"], ["10pt","10"], ["10.5pt","10.5"], ["11pt","11"], ["12pt","12"], ["14pt","14"], ["16pt","16"], ["18pt","18"], ["20pt","20"], ["22pt","22"], ["24pt","24"], ["26pt","26"], ["28pt","28"], ["36pt","36"], ["48pt","48"], ["72pt","72"] ]
lang["FormatBlock"]				= "段落样式"
lang["FormatBlockItem"]			= [ ["&lt;P&gt;", "普通"], ["&lt;H1&gt;", "标题一"], ["&lt;H2&gt;", "标题二"], ["&lt;H3&gt;", "标题三"], ["&lt;H4&gt;", "标题四"], ["&lt;H5&gt;", "标题五"], ["&lt;H6&gt;", "标题六"], ["&lt;p&gt;", "段落"], ["&lt;dd&gt;", "定义"], ["&lt;dt&gt;", "术语定义"], ["&lt;dir&gt;", "目录列表"], ["&lt;menu&gt;", "菜单列表"], ["&lt;PRE&gt;", "已编排格式"] ]
lang["ZoomSelect"]				= "缩放"

// Status Bar Button
lang["StatusModeCode"]			= "代码"
lang["StatusModeEdit"]			= "设计"
lang["StatusModeText"]			= "文本"
lang["StatusModeView"]			= "预览"

// Other
lang["FontSizeMenu"]			= "字号"
lang["FontNameMenu"]			= "字体"
lang["FormatBlockMenu"]			= "段落样式"



//#####################################
// Dialog
//#####################################


// About Dialog
lang["DlgAbout"]				= "关于 - eWebEditor"
lang["DlgAboutVersion"]			= "版本"
lang["DlgAboutLicense"]			= "版权所有"
lang["DlgAboutInfo"]			= "更多关于eWebEditor在线编辑器的信息，请访问："

// Dialog Install eWebEditor ActiveX
lang["DlgActivex"]				= "安装/升级：eWebEditor 控件"
lang["DlgActivexMsg"]			= "使用此功能，您需要安装/升级 eWebEditor 控件程序。您可以选择以下两种方式安装 eWebEditor 控件："
lang["DlgActivexDown"]			= "下载安装"
lang["DlgActivexOk"]			= "安装完成！"
lang["DlgActivexLegend"]		= "安装提示"
lang["DlgActivexOnline"]		= "在线安装"
lang["DlgActivexOnlineDesc"]	= "通过浏览器自动安装，方便快捷。<span class=red>(推荐)</span>"
lang["DlgActivexDownDesc"]		= "下载一个安装程序到您的计算机，运行这个程序进行安装。<br>如果您的浏览器无法正确安装控件，请选择本方法。"

// Dialog Install eWebEditorPrinter
lang["DlgPrinter"]				= "安装：eWebEditorPrinter"
lang["DlgPrinterMsg"]			= "使用此功能，您需要先安装基于虚拟打印技术的 eWebEditor 文档图形转换驱动程序。然后，您就可以把文档转换为与打印效果完全相同的图片格式文件。"
lang["DlgPrinterDown"]			= "下载安装"
lang["DlgPrinterDownDesc"]		= "点击下载一个安装程序到您的计算机，双击运行这个程序进行安装。"
lang["DlgPrinterOk"]			= "安装完成！"

// Anchor Dialog
lang["DlgAnchor"]				= "标签管理"
lang["DlgAnchorNoName"]			= "请输入书签名称！"
lang["DlgAnchorNoSelected"]		= "请先选择一个书签！"
lang["DlgAnchorName"]			= "书签名称"
lang["DlgAnchorOther"]			= "本页其它书签"

// BackImage Dialog
lang["DlgBkImg"]				= "背景图属性"
lang["DlgBkImgSource"]			= "图片来源"
lang["DlgBkImgCancelBg"]		= "取消背景图"
lang["DlgBkImgEffect"]			= "显示效果"
lang["DlgBkImgRepeat"]			= "平铺方式"
lang["DlgBkImgRepeatR"]			= "纵向横向"
lang["DlgBkImgRepeatNo"]		= "不平铺"
lang["DlgBkImgRepeatX"]			= "横向"
lang["DlgBkImgRepeatY"]			= "纵向"
lang["DlgBkImgAttach"]			= "滚动固定"
lang["DlgBkImgAttachScroll"]	= "滚动"
lang["DlgBkImgAttachFixed"]		= "固定"

// BackImage Dialog System Image
lang["DlgBkImgSnow"]			= "雪花"
lang["DlgBkImgNature"]			= "自然"
lang["DlgBkImgClear"]			= "晴朗"
lang["DlgBkImgGlacier"]			= "冰川"
lang["DlgBkImgFiesta"]			= "节日"
lang["DlgBkImgBirthday"]		= "生日"
lang["DlgBkImgCitrus"]			= "秋叶"
lang["DlgBkImgHearts"]			= "心型"
lang["DlgBkImgFlower"]			= "鲜花"
lang["DlgBkImgGathering"]		= "花纹"
lang["DlgBkImgChristmas"]		= "圣诞节"
lang["DlgBkImgIvy"]				= "常春藤"
lang["DlgBkImgTech"]			= "技术型"
lang["DlgBkImgMaize"]			= "黄色旋纹"
lang["DlgBkImgGrid"]			= "绿色方格"

// Emot Dialog
lang["DlgEmot"]					= "插入表情图标"

// Fieldset Dialog
lang["DlgFs"]					= "栏目框属性"
lang["DlgFsFieldset"]			= "栏目对齐"
lang["DlgFsLegend"]				= "标题对齐"

// Dialog HR
lang["DlgHr"]					= "水平尺"

// File Dialog
lang["DlgFile"]					= "文件属性"
lang["DlgFileSource"]			= "文件来源"

// Find/Replace Dialog
lang["DlgFR"]					= "查找 / 替换"
lang["DlgFRNoKey"]				= "请输入查找内容"
lang["DlgFRRestart"]			= "搜索完成，是否要从顶部开始重新搜索？"
lang["DlgFRNoFound"]			= "要查找的内容没有找到"
lang["DlgFRReplaceOK"]			= "处文本被替换成功"
lang["DlgFRSearchKey"]			= "查询内容"
lang["DlgFRReplaceKey"]			= "替换内容"
lang["DlgFRMatchCase"]			= "区分大小写"
lang["DlgFRMatchWord"]			= "全部匹配"
lang["DlgFRFindNext"]			= "查找下一个"
lang["DlgFRReplace"]			= "替换"
lang["DlgFRReplaceAll"]			= "全部替换"

// Flash Dialog
lang["DlgFlash"]				= "Flash动画属性"
lang["DlgFlashSource"]			= "Flash来源"
lang["DlgFlashEffect"]			= "显示效果"
lang["DlgFlashWidth"]			= "显示宽度"
lang["DlgFlashHeight"]			= "显示高度"
lang["DlgFlashPlay"]			= "自动播放"
lang["DlgFlashLoop"]			= "自动循环"
lang["DlgFlashMenu"]			= "完整菜单"
lang["DlgFlashQuality"]			= "品质"
lang["DlgFlashScale"]			= "比例"
lang["DlgFlashQuLow"]			= "低品质"
lang["DlgFlashQuAutoLow"]		= "自动低品质"
lang["DlgFlashQuMedium"]		= "中等品质"
lang["DlgFlashQuAutoHigh"]		= "自动高品质"
lang["DlgFlashQuHigh"]			= "高品质"
lang["DlgFlashQuBest"]			= "最佳品质"
lang["DlgFlashScShowall"]		= "全部显示"
lang["DlgFlashScNoborder"]		= "无边框"
lang["DlgFlashScExactfit"]		= "严格匹配"
lang["DlgFlashWMode"]			= "视窗模式"
lang["DlgFlashWmWindow"]		= "窗口"
lang["DlgFlashWmOpaque"]		= "不透明"
lang["DlgFlashWmTransparent"]	= "透明"
lang["DlgFlashVars"]			= "传入参数"
lang["DlgFlashErrBgColor"]		= "提示：\n\n无效的背景颜色值！"

// Fullscreen Dialog
lang["DlgFullscreen"]			= "eWebEditor - 全屏编辑"

// Hyperlink Dialog
lang["DlgHylnk"]				= "超级链接属性"
lang["DlgHylnkNoUrl"]			= "链接地址不能为空"
lang["DlgHylnkLegend"]			= "超级链接信息"
lang["DlgHylnkProtocol"]		= "链接类型"
lang["DlgHylnkTarget"]			= "链接目标"
lang["DlgHylnkTargetNone"]		= "默认(无)"
lang["DlgHylnkTargetSelf"]		= "相同框架"
lang["DlgHylnkTargetTop"]		= "整页"
lang["DlgHylnkTargetBlank"]		= "新建窗口"
lang["DlgHylnkTargetParent"]	= "父框架"
lang["DlgHylnkUrl"]				= "链接地址"
lang["DlgHylnkAnchor"]			= "书签链接"
lang["DlgHylnkAnchorNone"]		= "默认(无)"

// Iframe Dialog
lang["DlgIframe"]				= "网页帧属性"
lang["DlgIframeProperty"]		= "属性设置"
lang["DlgIframeUrl"]			= "网页地址"
lang["DlgIframeScroll"]			= "滚 动 条"
lang["DlgIframeYes"]			= "有"
lang["DlgIframeNo"]				= "无"
lang["DlgIframeBorder"]			= "边 框 线"
lang["DlgIframeMarginHeight"]	= "上下边距"
lang["DlgIframeMarginWidth"]	= "左右边距"
lang["DlgIframeWidth"]			= "帧 宽 度"
lang["DlgIframeHeight"]			= "帧 高 度"
lang["DlgIframeErrUrl"]			= "无效的网页地址！"
lang["DlgIframeErrWidth"]		= "无效的帧宽度！"
lang["DlgIframeErrHeight"]		= "无效的帧高度！"

// Image Dialog
lang["DlgImg"]					= "图片属性"
lang["DlgImgErrBorColor"]		= "提示：\n\n无效的边框颜色值！"
lang["DlgImgSource"]			= "图片来源"
lang["DlgImgEffect"]			= "显示效果"
lang["DlgImgAlt"]				= "说明文字"
lang["DlgImgBorder"]			= "边框粗细"
lang["DlgImgBorderColor"]		= "边框颜色"
lang["DlgImgSpecEffect"]		= "特殊效果"
lang["DlgImgAlpha1"]			= "半透明"
lang["DlgImgAlpha2"]			= "线型透明"
lang["DlgImgAlpha3"]			= "放射透明"
lang["DlgImgBlur1"]				= "模糊效果"
lang["DlgImgBlur2"]				= "风动模糊"
lang["DlgImgWave"]				= "正弦波纹"
lang["DlgImgGray"]				= "黑白照片"
lang["DlgImgChroma"]			= "白色透明"
lang["DlgImgDropShadow"]		= "投射阴影"
lang["DlgImgShadow"]			= "阴影"
lang["DlgImgGlow"]				= "发光"
lang["DlgImgFlipv"]				= "垂直翻转"
lang["DlgImgFliph"]				= "左右翻转"
lang["DlgImgGrays"]				= "降低彩色"
lang["DlgImgXray"]				= "X光照片"
lang["DlgImgInvert"]			= "底片"
lang["DlgImgWidth"]				= "图片宽度"
lang["DlgImgHeight"]			= "图片高度"
lang["DlgImgVSpace"]			= "上下间距"
lang["DlgImgHSpace"]			= "左右间距"
lang["DlgImgPreview"]			= "预览"
lang["DlgImgSYFlag"]			= "启用水印"

// Map Dialog
lang["DlgMap"]					= "图形热点链接"
lang["DlgMapNew"]				= "新建"
lang["DlgMapDesc"]				= "双击可编辑链接"

// Marquee Dialog
lang["DlgMarquee"]				= "字幕属性"
lang["DlgMarqueeText"]			= "文本"
lang["DlgMarqueeBehavior"]		= "表现"
lang["DlgMarqueeScroll"]		= "滚动条"
lang["DlgMarqueeSlide"]			= "幻灯片"
lang["DlgMarqueeAlternate"]		= "交替"

// Media Dialog
lang["DlgMedia"]				= "媒体文件属性"
lang["DlgMediaSource"]			= "媒体文件来源"
lang["DlgMediaEffect"]			= "播放效果"
lang["DlgMediaWidth"]			= "播放宽度"
lang["DlgMediaHeight"]			= "播放高度"
lang["DlgMediaPlugin"]			= "插件类型"
lang["DlgMediaPluginAuto"]		= "自动选择"
lang["DlgMediaPluginWMP6"]		= "Windows Media Player V6 播放插件"
lang["DlgMediaPluginWMP7"]		= "Windows Media Player V7+ 播放插件"
lang["DlgMediaPluginReal"]		= "RealPlayer 播放插件"
lang["DlgMediaPluginQT"]		= "QuickTime 播放插件"
lang["DlgMediaPluginFLV"]		= "FLV 播放插件"
lang["DlgMediaAutoStart"]		= "自动播放"
lang["DlgMediaMsgPlugin"]		= "未知文件类型，请指定您想使用的媒体播放插件。"
lang["DlgMediaPreviewImg"]		= "预览图片"
lang["DlgMediaPreviewImgDesc"]	= "此项仅在使用[FLV播放插件]时有效"

// SelColor Dialog
lang["DlgSelCor"]				= "颜色选择"
lang["DlgSelCorForecolor"]		= "字体前景色"
lang["DlgSelCorBackcolor"]		= "字体背景色"
lang["DlgSelCorBgcolor"]		= "对象背景色"
lang["DlgSelCorSel"]			= "选中色彩"
lang["DlgSelCorBase"]			= "基色"
lang["DlgSelCorLight"]			= "亮度"
lang["DlgSelCorCode"]			= "代码"

// Symbol Dialog
lang["DlgSymbol"]				= "插入特殊符号"
lang["DlgSymbolPreview"]		= "预览"

// Table Dialog
lang["DlgTab"]					= "表格属性"
lang["DlgTabInvalidRow"]		= "无效的行数，至少要1行！"
lang["DlgTabInvalidCol"]		= "无效的列数，至少要1列！"
lang["DlgTabInvalidWidth"]		= "无效的表格宽度！"
lang["DlgTabInvalidHeight"]		= "无效的表格高度！"
lang["DlgTabRowsCols"]			= "表格大小"
lang["DlgTabRows"]				= "表格行数"
lang["DlgTabCols"]				= "表格列数"
lang["DlgTabLayout"]			= "表格布局"
lang["DlgTabBorder"]			= "边框粗细"
lang["DlgTabBorderCollapse"]	= "边框效果"
lang["DlgTabBCseparate"]		= "分开"
lang["DlgTabBCcollapse"]		= "合并"
lang["DlgTabCellspacing"]		= "单元间距"
lang["DlgTabCellpadding"]		= "单元边距"
lang["DlgTabSize"]				= "表格尺寸"
lang["DlgTabChkWidth"]			= "指定表格的宽度"
lang["DlgTabChkHeight"]			= "指定表格的高度"
lang["DlgTabStyle"]				= "表格样式"
lang["DlgTabBorderStyle"]		= "边框样式"
lang["DlgTabBgImage"]			= "背景图片"

// Table Cell/Row Dialog
lang["DlgTabCelErrWidth"]		= "无效的宽度！"
lang["DlgTabCelErrHeight"]		= "无效的高度！"
lang["DlgTabCelLayout"]			= "布局"
lang["DlgTabCelHAlign"]			= "水平对齐"
lang["DlgTabCelVAlign"]			= "垂直对齐"
lang["DlgTabCelSize"]			= "尺寸"
lang["DlgTabCelChkWidth"]		= "指定宽度"
lang["DlgTabCelChkHeight"]		= "指定高度"
lang["DlgTabCelStyle"]			= "样式"
lang["DlgTabCelBorderStyle"]	= "边框样式"
lang["DlgTabCelBgImage"]		= "背景图片"

// Table Cell Split Dialog
lang["DlgCelSpt"]				= "单元格拆分"
lang["DlgCelSptCols"]			= "列数"
lang["DlgCelSptRows"]			= "行数"
lang["DlgCelSptErrRowCol"]		= "无效的行列数，必须大于1！"
lang["DlgCelSptSplitCol"]		= "拆分为列"
lang["DlgCelSptSplitRow"]		= "拆分为行"

// Dialog Button
lang["DlgBtnClose"]				= "关闭"
lang["DlgBtnOK"]				= "确定"
lang["DlgBtnCancel"]			= "取消"
lang["DlgBtnGoto"]				= "转到"
lang["DlgBtnDel"]				= "删除"
lang["DlgBtnBrowse"]			= "浏览..."

// Dialog Common
lang["DlgComTable"]				= "表格"
lang["DlgComTableCell"]			= "单元格"
lang["DlgComTableRow"]			= "表格行"
lang["DlgComSet"]				= "设置"
lang["DlgComBody"]				= "网页"
lang["DlgComDefault"]			= "默认"
lang["DlgComUploading"]			= "...上传中...请等待..."
lang["DlgComInsert"]			= "插入"
lang["DlgComModify"]			= "修改"
lang["DlgComTitle"]				= "标题"
lang["DlgComContent"]			= "内容"
lang["DlgComOther"]				= "其它"
lang["DlgComNone"]				= "无"
lang["DlgComPx"]				= "像素"
lang["DlgComPer"]				= "百分比"
lang["DlgComAttribute"]			= "属性"
lang["DlgComYes"]				= "是"
lang["DlgComNo"]				= "否"
lang["DlgComInsertCursor"]		= "当前位置插入"
lang["DlgComInsertReplace"]		= "替换当前内容"
lang["DlgComVSpace"]			= "垂直间距"
lang["DlgComHSpace"]			= "水平间距"
lang["DlgComWidth"]				= "宽度"
lang["DlgComHeight"]			= "高度"
lang["DlgComColor"]				= "颜色"
lang["DlgComAlign"]				= "对齐"
lang["DlgComBgColor"]			= "背景颜色"
lang["DlgComPreview"]			= "预览"
lang["DlgComClose"]				= "关闭"
lang["DlgComTabNormal"]			= "常规设置"
lang["DlgComTabMFU"]			= "批量上传"
lang["DlgComMFUMsgAllow"]		= "说明：批量上传允许文件类型：<ext>，允许文件大小：<size>。"
lang["DlgComMFUMsgNotInstall"]	= "批量上传控件未安装或版本太旧，暂不能使用。"
lang["DlgComMFUMsgInstallOk"]	= "批量上传控件已安装成功！"
lang["DlgComMFUMsgBtnOk"]		= "开始使用"
lang["DlgComNotice"]			= "提示："

// Dialog Align
lang["DlgAlign"]				= "对齐方式"
lang["DlgAlignText"]			= "文字对齐"
lang["DlgAlignLeft"]			= "左对齐"
lang["DlgAlignRight"]			= "右对齐"
lang["DlgAlignCenter"]			= "居中对齐"
lang["DlgAlignFull"]			= "两端对齐"
lang["DlgAlignTop"]				= "顶部"
lang["DlgAlignMiddle"]			= "中部"
lang["DlgAlignBottom"]			= "底部"
lang["DlgAlignAbsmiddle"]		= "绝对居中"
lang["DlgAlignAbsbottom"]		= "绝对底部"
lang["DlgAlignBaseline"]		= "基线"
lang["DlgAlignTexttop"]			= "文本顶部"

// Dialog Color
lang["DlgColor"]				= "颜色属性"
lang["DlgColorBorder"]			= "边框颜色"
lang["DlgColorBg"]				= "背景颜色"

// Dialog From
lang["DlgFromFile"]				= "上传"
lang["DlgFromUrl"]				= "网络"
lang["DlgFromSys"]				= "系统"

// Dialog Line
lang["DlgLineSolid"]			= "实线"
lang["DlgLineDotted"]			= "虚线"
lang["DlgLineDashed"]			= "破折号"
lang["DlgLineDouble"]			= "双线"
lang["DlgLineGroove"]			= "凹线"
lang["DlgLineRidge"]			= "凸线"
lang["DlgLineInset"]			= "嵌入"
lang["DlgLineOutset"]			= "开端"

// Dialog EQ
lang["DlgEQ"]					= "公式"
lang["DlgEQBackground"]			= "背景颜色"
lang["DlgEQForeground"]			= "字体颜色"
lang["DlgEQInstallAlt"]			= "要使用此功能，必须安装 WebEQ 公式编辑插件。在弹出窗口中选“是”，以完成此插件的安装。安装完成后，下次打开此窗口即可正常使用此功能了。"

// Dialog Art
lang["DlgArt"]					= "艺术字"
lang["DlgArtFontFamily"]		= "字体"
lang["DlgArtFontSize"]			= "大小"
lang["DlgArtText"]				= "文字"
lang["DlgArtDefaultFamily"]		= "宋体"
lang["DlgArtDefaultText"]		= "请在此键入您自己的内容"
lang["DlgArtMsgNull"]			= "文字内容不允许为空！"

// Dialog Paragraph
lang["DlgPar"]					= "段落属性"
lang["DlgPraMargin"]			= "空白"
lang["DlgPraMarginTop"]			= "段前"
lang["DlgPraMarginBottom"]		= "段后"
lang["DlgPraMarginLeft"]		= "文本之前"
lang["DlgPraMarginRight"]		= "文本之后"
lang["DlgPraOther"]				= "其它"
lang["DlgPraLineHeight"]		= "行距大小"
lang["DlgPraTextIndent"]		= "首行缩进"
lang["DlgPraWordSpacing"]		= "单字间距"
lang["DlgPraLH1"]				= "单倍行距"
lang["DlgPraLH15"]				= "1.5 倍行距"
lang["DlgPraLH2"]				= "2 倍行距"
lang["DlgPraLHOther"]			= "多倍行距"

// Dialog Browse
lang["DlgBrowse"]				= "文件浏览"
lang["DlgBrowseImage"]			= "图片"
lang["DlgBrowseFlash"]			= "Flash"
lang["DlgBrowseMedia"]			= "媒体"
lang["DlgBrowseFile"]			= "所有文件"
lang["DlgBrowseSort"]			= "排序"
lang["DlgBrowseSortName"]		= "文件名称"
lang["DlgBrowseSortSize"]		= "文件大小"
lang["DlgBrowseSortType"]		= "文件类型"
lang["DlgBrowseSortTime"]		= "修改时间"
lang["DlgBrowseSortASC"]		= "正序"
lang["DlgBrowseSortDESC"]		= "倒序"
lang["DlgBrowseView"]			= "查看"
lang["DlgBrowseViewDetails"]	= "详细资料"
lang["DlgBrowseViewThumbnails"]	= "缩略图"
lang["DlgBrowseViewIcons"]		= "图标"
lang["DlgBrowseViewList"]		= "列表"
lang["DlgBrowseUploadImage"]	= "上传图片库"
lang["DlgBrowseUploadFlash"]	= "上传Flash库"
lang["DlgBrowseUploadMedia"]	= "上传媒体库"
lang["DlgBrowseUploadFile"]		= "上传的文件"
lang["DlgBrowseShareImage"]		= "共享图片库"
lang["DlgBrowseShareFlash"]		= "共享Flash库"
lang["DlgBrowseShareMedia"]		= "共享媒体库"
lang["DlgBrowseShareFile"]		= "共享的文件"
lang["DlgBrowseNoSelected"]		= "请先选择一个文件！"
lang["DlgBrowsePage"]			= "分页"
lang["DlgBrowsePageAll"]		= "所有"
lang["DlgBrowsePageFirst"]		= "首页"
lang["DlgBrowsePagePre"]		= "上页"
lang["DlgBrowsePageNext"]		= "下页"
lang["DlgBrowsePageLast"]		= "尾页"

// Dialog Import Word
lang["DlgWord"]					= "导入Word文档"
lang["DlgWordLegend"]			= "Word选项"
lang["DlgWordFile"]				= "文件"
lang["DlgWordAPI"]				= "接口"
lang["DlgWordAPI0"]				= "自动处理"
lang["DlgWordAPI1"]				= "微软Office Word"
lang["DlgWordAPI2"]				= "金山WPS文字"
lang["DlgWordInvalidFile"]		= "无效的Word文档文件，请选择！"
lang["DlgWordImporting"]		= "...Word文档导入中...请等待..."
lang["DlgWordOptimize"]			= "优化选项"
lang["DlgWordOpt1"]				= "选择优化模式 (除以下选项外的其它所有效果都将被保留)"
lang["DlgWordOpt1VML"]			= "去除VML"
lang["DlgWordOpt1Absolute"]		= "去除浮动"
lang["DlgWordOpt1EQ"]			= "公式优化"
lang["DlgWordOpt1Margin"]		= "边距优化"
lang["DlgWordOpt1Space"]		= "去除空行"
lang["DlgWordOpt1Grid"]			= "去除网格"
lang["DlgWordOpt2"]				= "全部清除模式 (除以下选项外的其它所有效果都将被清除)"
lang["DlgWordOpt2Image"]		= "保留图片"
lang["DlgWordOpt2Table"]		= "表格优化"
lang["DlgWordOpt2EQ"]			= "公式优化"
lang["DlgWordOpt2Indent"]		= "首行缩进"
lang["DlgWordOpt2PtoBR"]		= "P转为BR"
lang["DlgWordPaste"]			= "粘贴"
lang["DlgWordPage"]				= "导入页面效果"
lang["DlgWordPageWidth"]		= "导入页宽"
lang["DlgWordPageMargin"]		= "页边距"
lang["DlgWordPageEffect"]		= "边框效果"
lang["DlgWordPageScroll"]		= "自动滚动"
lang["DlgWordModeHTML"]			= "HTML图文格式"
lang["DlgWordModeIMG"]			= "纯图片格式"
lang["DlgWordImgType"]			= "图片类型"
lang["DlgWordImgAlt"]			= "注：此模式下所有文字将转为图片，不可再编辑。"
lang["DlgWordImgEfFlag"]		= "启用文档效果"
lang["DlgWordImgEfWidth"]		= "宽度"
lang["DlgWordImgEfHeight"]		= "高度"

// Dialog Import Excel
lang["DlgExcel"]				= "导入Excel电子表格"
lang["DlgExcelLegend"]			= "Excel选项"
lang["DlgExcelFile"]			= "文　件"
lang["DlgExcelAPI"]				= "接　口"
lang["DlgExcelAPI0"]			= "自动处理"
lang["DlgExcelAPI1"]			= "微软Office Excel"
lang["DlgExcelAPI2"]			= "金山WPS表格"
lang["DlgExcelSheet"]			= "工作表"
lang["DlgExcelSheetAll"]		= "所有..."
lang["DlgExcelInvalidFile"]		= "无效的Excel文件，请选择！"
lang["DlgExcelImporting"]		= "...Excel导入中...请等待..."
lang["DlgExcelOptimize"]		= "优化选项"
lang["DlgExcelOpt1"]			= "选择优化模式 (除以下选项外的其它所有效果都将被保留)"
lang["DlgExcelOpt1VML"]			= "去除VML"
lang["DlgExcelOpt1Space"]		= "去除空行"
lang["DlgExcelOpt1Table"]		= "表格优化"
lang["DlgExcelOpt1Overflow"]	= "自动滚动"
lang["DlgExcelOpt2"]			= "全部清除模式 (除以下选项外的其它所有效果都将被清除)"
lang["DlgExcelOpt2Image"]		= "保留图片"
lang["DlgExcelOpt2Space"]		= "去除空行"
lang["DlgExcelOpt2Table"]		= "表格加线"

// Dialog OWC Excel
lang["DlgOWCExcel"]				= "插入Excel电子表格"
lang["DlgOWCExcelProperty"]		= "属性选项"
lang["DlgOWCExcelVersion"]		= "插件版本"
lang["DlgOWCExcelWidth"]		= "插件宽度"
lang["DlgOWCExcelHeight"]		= "插件高度"
lang["DlgOWCExcelNoOWC"]		= "要交互式地使用此网页，您必须装有："

// Dialog Template
lang["DlgTemplate"]				= "插入模板"
lang["DlgTemplateOption"]		= "可选模板"
lang["DlgTemplatePreview"]		= "预览"

// Dialog I_Upload
lang["DlgIUpload"]				= "上传"
lang["DlgIUploadImage"]			= "图片"
lang["DlgIUploadFlash"]			= "Flash"
lang["DlgIUploadMedia"]			= "媒体"
lang["DlgIUploadFile"]			= "文件"
lang["DlgIUploadOpt"]			= "选项"
lang["DlgIUploadErrLink"]		= "无效参数：链接表单项(link)"

// Dialog QuickFormat
lang["DlgQF"]					= "一键排版"
lang["DlgQFPaste"]				= "粘贴"
lang["DlgQFKeepAll"]			= "保留所有"
lang["DlgQFKeep"]				= "保留选项"
lang["DlgQFKeepUl"]				= "保留列表"
lang["DlgQFKeepTable"]			= "保留表格"
lang["DlgQFKeepImg"]			= "保留图片"
lang["DlgQFKeepA"]				= "保留超链接"
lang["DlgQFKeepObject"]			= "保留对象"
lang["DlgQFDel"]				= "去除选项"
lang["DlgQFDelLine"]			= "去除空行"
lang["DlgQFDelSpace"]			= "去除多余空格"
lang["DlgQFDelHidden"]			= "去除隐藏域"
lang["DlgQFDelAllAttr"]			= "去除所有属性"
lang["DlgQFDelStyle"]			= "去除样式属性"
lang["DlgQFDelOn"]				= "去除事件属性"
lang["DlgQFAdd"]				= "增效选项"
lang["DlgQFAddMargin"]			= "段前段后置0"
lang["DlgQFAddIndent"]			= "首行缩进2字"
lang["DlgQFAddJustify"]			= "两端对齐"
lang["DlgQFAddLineHeight"]		= "行距"
lang["DlgQFAddBR2P"]			= "&lt;BR&gt;转&lt;P&gt;"
lang["DlgQFAddTableBC"]			= "单线表格"
lang["DlgQFAddImgCenter"]		= "图片居中"
lang["DlgQFConfusion"]			= "去除干扰字"
lang["DlgQFConfusionAuto"]		= "自动检测"
lang["DlgQFConfusionSuper"]		= "自动检测+源分析"
lang["DlgQFConfusionColor"]		= "干扰字色"
lang["DlgQFConfusionClass"]		= "干扰字类"
lang["DlgQFAddMarginTop"]		= "段前"
lang["DlgQFAddMarginBottom"]	= "段后"
lang["DlgQFAddFontName"]		= "字体"
lang["DlgQFAddFontSize"]		= "字号"

// Dialog Paste Options
lang["DlgPaste"]				= "选择性粘贴"
lang["DlgPasteOpt"]				= "格式选项"
lang["DlgPasteOptImg"]			= "图片格式"
lang["DlgPasteOptHtml"]			= "HTML格式"
lang["DlgPasteOptText"]			= "纯文字格式"
lang["DlgPasteOptFile"]			= "多图片文件格式"
lang["DlgPasteFileExt"]			= "支持文件格式"
lang["DlgPasteFileSize"]		= "支持文件大小"
lang["DlgPasteFileUploading"]	= "...多文件上传中...请等待..."

// Dialog Paste Gecko
lang["DlgPasteGecko"]			= "粘贴"
lang["DlgPasteGeckoText"]		= "粘贴为纯文本格式"
lang["DlgPasteGeckoMsg"]		= "请使用键盘快捷键(Ctrl+V)把内容粘贴到下面的方框里，再按“确定”。"
lang["DlgPasteGeckoSecurity"]	= "因为您的浏览器的安全设置原因，本编辑器不能直接访问您的剪贴板内容，您需要在本窗口重新粘贴一次。"

// Dialog Pagination
lang["DlgPagi"]					= "分页管理"
lang["DlgPagiTitle"]			= "分页标题"
lang["DlgPagiTitleUp"]			= "向上"
lang["DlgPagiTitleDown"]		= "向下"
lang["DlgPagiTitleModi"]		= "修改"
lang["DlgPagiAuto"]				= "自动分页"
lang["DlgPagiAutoNum"]			= "每页最少文字数"
lang["DlgPagiAutoBtn"]			= "自动重新分页"
lang["DlgPagiKey"]				= "分页符"
lang["DlgPagiKeyInsert"]		= "插入分页符"
lang["DlgPagiKeyEmpty"]			= "清空分页符"

// Dialog Image1
lang["DlgImage1"]				= "上传图片"

// Dialog Import PPT
lang["DlgPPT"]					= "导入PPT文档"
lang["DlgPPTLegend"]			= "文件选项"
lang["DlgPPTOptimize"]			= "导入选项"
lang["DlgPPTInvalidFile"]		= "无效的PPT文档文件，请选择！"
lang["DlgPPTtwFlag"]			= "启用图片压缩"
lang["DlgPPTtw"]				= "宽度"
lang["DlgPPTth"]				= "高度将同比例缩放"
lang["DlgPPTFile"]				= "文件"
lang["DlgPPTAPI"]				= "接口"
lang["DlgPPTAPI0"]				= "自动处理"
lang["DlgPPTAPI1"]				= "微软Office PowerPoint"
lang["DlgPPTAPI2"]				= "金山WPS演示"
lang["DlgPPTImporting"]			= "...文档导入中...请等待..."

// Dialog Container
lang["DlgDlgTitle"]				= "对话框加载中..."



//#####################################
// Message
//#####################################
lang["ErrNoLinkField"]			= "调用错误：请传入调用参数ID，即隐藏的内容表单项ID！"
lang["ErrInvalidStyle"]			= "调用错误：请传入有效的样式名！"
lang["ErrUploadInvalidExt"]		= "提示：\n\n请选择一个有效的文件，\n支持的格式有"
lang["ErrUploadInvalidFile"]	= "请选择有效的上传文件！"
lang["ErrUploadSizeLimit"]		= "您上传的文件大小超出了最大限制"
lang["ErrUploadSpaceLimit"]		= "您的上传文件空间已经达到了最大限制"
lang["ErrParam"]				= "错误参数调用！"
lang["ErrInputNull"]			= "不能为空！"
lang["ErrInput"]				= "无效输入值！"
lang["ErrLicense"]				= "未授权：功能被禁用，请先配置授权！"
lang["ErrInvalidFile"]			= "提示：\n\n请选择一个有效的文件，\n支持的格式有"

lang["MsgOnlyInEditMode"]		= "需转换为编辑状态后才能使用编辑功能！"
lang["MsgOnlyForIE"]			= "此功能只能在 IE 浏览器下使用！"
lang["MsgOnlyFor32Bit"]			= "此高级功能只能在 32位 浏览器下使用！"
lang["MsgCanotSetInViewMode"]	= "预览时不允许设置编辑区内容。"
lang["MsgNotCompatibleHtml"]	= "HTML编辑模式需要IE5.5版本以上的支持！"
lang["MsgNotCompatibleFunc"]	= "此功能需要IE5.5版本以上的支持！"
lang["MsgHtmlToText"]			= "警告！切换到纯文本模式会丢失您所有的HTML格式，您确认切换吗？"
lang["MsgHylnkLimit"]			= "链接只能是图片或文本"
lang["MsgMapLimit"]				= "热点链接只能作用于图片"
lang["MsgRemoteUploading"]		= "...远程文件收集中...请等待..."
lang["MsgLocalUploading"]		= "...本地文件上传中...请等待..."
lang["MsgNotParagraph"]			= "段落属性只能应用于段落，请至少选择一个段落！"
lang["MsgNoClient"]				= "您还未安装eWebEditor客户端控件, 请先安装再使用此功能！"
lang["MsgIeSpellDownload"]		= "拼写检查插件还没安装，你是否想现在就下载？"

lang["MsgSafeCut"]				= "您的浏览器安全设置不允许编辑器自动执行剪切操作，请使用键盘快捷键(Ctrl+X)来完成。"
lang["MsgSafeCopy"]				= "您的浏览器安全设置不允许编辑器自动执行复制操作，请使用键盘快捷键(Ctrl+C)来完成。"

lang["HtmlQuote"]				= "以下是引用片段："
lang["HtmlCode"]				= "以下是代码片段："

// Check Color
lang["ErrColorBorder"]			= "无效的边框颜色值！"
lang["ErrColorBg"]				= "无效的背景颜色值！"
lang["ErrColorInvalid"]			= "无效的颜色值！"



//#####################################
// Context Menu
//#####################################
lang["CMenuImg"]				= "图片属性..."
lang["CMenuParagraph"]			= "段落属性..."
lang["CMenuFlash"]				= "Flash属性..."
lang["CMenuMedia"]				= "媒体属性..."
lang["CMenuHr"]					= "水平尺属性..."
